[project]
name = "fast-api-cicd"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "bandit>=1.8.0",
    "fastapi[standard]>=0.115.6",
    "flake8>=7.1.1",
    "httpx>=0.28.1",
    "pytest>=8.3.4",
    "ruff>=0.8.6",
]
