name: fast-api-CICD

on:
  workflow_dispatch:
    inputs:
      path_to_dockerfile:
        description: path to dockerfile
        type: string
        default: "app/Dockerfile"
      docker_build_dir:
        description: path to run docker build
        type: string
        default: "app/"
      image_tag:
        description: tag to give image before pushing to GCP
        type: string
        default: fast-api-demo
      gcp_region:
        description: gcp region
        type: string
        default: us-central1
      artifact_registry_url:
        description: qualified url
        type: string
        default: us-central1-docker.pkg.dev/ci-cd-github-actions-447612/fast-api-cicd


concurrency: ci-${{ github.repository }}-docker-pipeline 

jobs:
  lint-and-scan:

    runs-on: ubuntu-latest

    steps:
      - name: clone repo
        uses: actions/checkout@v4
      

      - name: Install uv and set up python
        uses: astral-sh/setup-uv@v3
      
      - name: Lint python code
        run: uv run flake8 ./app/

      - name: Test with project python version/packages
        run: uv run --frozen pytest app/tests.py  

      - name: Run security code check
        run: uv run bandit --exclude ./app/tests.py -r ./app/

      - uses: pyupio/safety-action@v1
        with:
          api-key: ${{ secrets.SAFETY_API_KEY }}

  docker:
    needs: lint-and-scan
    
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone code
        uses: actions/checkout@v4

      - name: Authenticate via GCP/OIDC
        uses: 'google-github-actions/auth@v2'
        id: auth
        with:
          project_id: 'ci-cd-github-actions-447612'
          workload_identity_provider: 'projects/248413649642/locations/global/workloadIdentityPools/github-actions-pool/providers/github-actions-provider'

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
  
      - name: Configure Docker for Artifact Registry
        run: |-
          gcloud auth configure-docker us-central1-docker.pkg.dev
          
      - name: Build and Push Container
        run: |-
            docker build -t "${{ inputs.artifact_registry_url }}/${{ inputs.image_tag }}:${{ github.sha }}" ./
            docker push "${{ inputs.artifact_registry_url }}/${{ inputs.image_tag }}:${{ github.sha }}"